version: '3.3'
services:
  caddy-webdav:
    container_name: caddy-webdav
    volumes:
      - '${PWD}/webdav:/srv'
    ports:
      - '82:8080'
    image: sbkg0002/docker-caddy-webdav:v2-alpine
    restart: unless-stopped
    networks:
      - notes
